name: 新的想法
description: 提出关于改进 Seraphine 的任何想法
title: "[Enhancement] （删去左右圆括号，并在此处简要描述功能）"
labels: ["enhancement"]

body:
  - type: textarea
    id: description
    attributes:
      label: 功能描述
      description: 请简单介绍一下您的想法，可以结合图片来更好的解释它。
      placeholder: e.g. 我希望能够在 xxx 页面添加 xxx 功能，它能够让使用者更加......
    validations:
      required: true
  - type: checkboxes
    id: confirm-unduplicate
    attributes:
      label: 在提交之前，请您确认
      options:
        - label: 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法
          required: true
    validations:
      required: true
